# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BulkVectorExport
                                 A QGIS plugin
 export vector layers to common format and crs
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2018-12-08
        git sha              : $Format:%H$
        copyright            : (C) 2018 by Zoltan Siki
        email                : siki1958@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os.path
from qgis.PyQt.QtCore import (QSettings, QTranslator, qVersion, QCoreApplication)
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import (QAction, QMessageBox)
from qgis.core import (QgsVectorFileWriter, QgsProject, QgsMapLayer,
                        QgsLayerDefinition, QgsCoordinateTransform)

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .bulkvectorexport_dialog import BulkVectorExportDialog


class BulkVectorExport:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(self.plugin_dir, 'i18n',
            'BulkVectorExport_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)

            if qVersion() > '4.3.3':
                QCoreApplication.installTranslator(self.translator)

        # Create the dialog (after translation) and keep reference
        self.dlg = BulkVectorExportDialog()
        self.dlg.setModal(True)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&bulkvectorexport')
        # TODO: We are going to let the user set this up in a future iteration
        self.toolbar = self.iface.addToolBar(u'BulkVectorExport')
        self.toolbar.setObjectName(u'BulkVectorExport')

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
            :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('BulkVectorExport', message)


    def add_action(self, icon_path, text, callback, enabled_flag=True,
        add_to_menu=True, add_to_toolbar=True, status_tip=None,
        whats_this=None, parent=None):
        """Add a toolbar icon to the toolbar."""

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToVectorMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/bulkvectorexport/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Bulk Vector Export'),
            callback=self.run,
            parent=self.iface.mainWindow())


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginVectorMenu(
                self.tr(u'&bulkvectorexport'),
                action)
            self.iface.removeToolBarIcon(action)
        # remove the toolbar
        del self.toolbar


    def run(self):
        """Run method that performs all the real work"""
        # show the dialog
        self.dlg.show()
        # Run the dialog event loop safely on both PyQt5 (exec_()) and PyQt6 (exec())
        exec_method = getattr(self.dlg, 'exec', getattr(self.dlg, 'exec_', None))
        result = exec_method()
        if result:
            # get directory name
            dirName = self.dlg.dirEdit.text().strip()
            # get ogr driver name
            ogr_driver_name = self.dlg.formatBox.currentText()
            exportOnlySelected = self.dlg.onlySelected.isChecked()
            print('Selected: ', exportOnlySelected)
            sldExport = self.dlg.sldExport.isChecked()
            qlrExport = self.dlg.qlrExport.isChecked()
            qmlExport = self.dlg.qmlExport.isChecked()
            
            crs = QgsProject.instance().crs()
            
            for layer in self.iface.mapCanvas().layers():
                if layer.type() == QgsMapLayer.VectorLayer:
                    print('Writing:' + layer.name())
                    layer_filename = os.path.join(dirName, layer.name())
                    if self.dlg.layerCrsButton.isChecked():
                        crs = layer.crs()
                        print('CRS selected: ', crs.description())
                    
                    # Setup cross-version compatible Save Options block
                    options = QgsVectorFileWriter.SaveVectorOptions()
                    options.driverName = ogr_driver_name
                    options.fileEncoding = layer.dataProvider().encoding()
                    options.onlySelectedFeatures = exportOnlySelected
                    
                    # If the user chose a specific CRS, assign it to the options block
                    if self.dlg.layerCrsButton.isChecked():
                        options.onlySelectedFeatures = exportOnlySelected
                    else:
                        # Otherwise, use the project instance CRS defined above
                        options.ct = QgsCoordinateTransform(layer.crs(), crs, QgsProject.instance())
                    
                    # QGIS 3 and 4 safe export call
                    err, errorMessage, newFilename, newLayerName = QgsVectorFileWriter.writeAsVectorFormatV3(
                        layer,
                        layer_filename,
                        QgsProject.instance().transformContext(),
                        options
                    )
                    # QgsVectorFileWriter.NoError equals 0
                    if err != QgsVectorFileWriter.NoError:
                        QMessageBox.warning(self.dlg, "BulkVectorExport",
                                            "Failed to export: " + layer.name() + 
                                            " Status Error Code: " + str(err) +
                                            " Message: " + errorMessage)
                    else:
                        if sldExport:
                            # export SLD if layer was exported with success
                            layer.saveSldStyle(layer_filename + '.sld')
                        if qlrExport:
                            # export QGIS layer definition (qlr)
                            node = QgsProject.instance().layerTreeRoot().findLayer(layer.id())
                            QgsLayerDefinition.exportLayerDefinition(
                                layer_filename + '.qlr', [node])
                        if qmlExport:
                            qml = os.path.splitext(layer_filename)[0] + '.qml'
                            layer.saveNamedStyle(qml)
